# Generated by Django 4.1.1 on 2023-01-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_admin_alter_room_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
