# Generated by Django 4.1.1 on 2023-02-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_room_members_alter_room_admin_roommember'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.TextField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
