# Generated by Django 4.1.7 on 2023-04-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default='username', max_length=64),
            preserve_default=False,
        ),
    ]
